version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/mydb
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres_data:
