openapi: 3.0.0
info:
  title: Bitespeed API
  description: API documentation for Bitespeed identity reconciliation service.
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /identify:
    post:
      summary: Identify contact
      description: Identify and consolidate contact information.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: mcfly@hillvalley.edu
                phoneNumber:
                  type: string
                  example: "123456"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  contact:
                    type: object
                    properties:
                      primaryContactId:
                        type: integer
                        example: 1
                      emails:
                        type: array
                        items:
                          type: string
                        example: ["lorraine@hillvalley.edu", "mcfly@hillvalley.edu"]
                      phoneNumbers:
                        type: array
                        items:
                          type: string
                        example: ["123456"]
                      secondaryContactIds:
                        type: array
                        items:
                          type: integer
                        example: [23]
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: string
                example: "Email or phone number is required"
